myenv/myblog/myblog/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

palitot/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('',include('portfolio.urls') ),
    path('admin/', admin.site.urls)
    ]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

portfolio/urls.py
# portfolio/urls.py
from django.urls import path
from .views import home, about, project_list, project_detail

app_name = 'portfolio'

urlpatterns = [
    path('', project_list, name='project_list'),
    path('about/', about, name='about'),
    path('projects/', project_list, name='project_list'),
    path('projects/<int:projeto_id>/', project_detail, name='project_detail'),
]

myenv/myblog/posts/models.py
from django.db import models

# Create your models here.

portfolio/models.py
from django.db import models

class Projeto(models.Model):
    nome = models.CharField(max_length=200, blank=True, default='')
    cliente = models.TextField(blank=True, default='')
    descricao = models.TextField(blank=True, default='')
    link_youtube = models.URLField(blank=True)

    def __str__(self):
        return self.nome

class Imagem(models.Model):
    projeto = models.ForeignKey(Projeto, on_delete=models.CASCADE, blank=True, default=None)
    imagem = models.ImageField(upload_to='imagens/', blank=True)
    descricao = models.TextField(blank=True, default='')

    def __str__(self):
        return self.descricao

myenv/myblog/posts/views.py
from django.shortcuts import render

# Create your views here.

portfolio/views.py
# portfolio/views.py
from django.shortcuts import render, get_object_or_404
from .models import Projeto, Imagem

def home(request):
    return render(request, 'home.html')

def about(request):
    return render(request, 'about.html')

def project_list(request):
    projetos = Projeto.objects.all()
    return render(request, 'project_list.html', {'projetos': projetos})

def project_detail(request, projeto_id):
    projeto = get_object_or_404(Projeto, pk=projeto_id)
    imagens = Imagem.objects.filter(projeto=projeto)
    link_youtube = projeto.link_youtube
    youtube_id = link_youtube.split('=')[-1]

    context = {
        'projeto': projeto,
        'imagens': imagens,
        'youtube_id': youtube_id,
    }
    return render(request, 'project_detail.html', context)

portfolio/templates/about.html
{% extends 'base.html' %}

{% block content %}
<div class="container-fluid mt-5">
  <div class="row">
    <div class="col-md-8">
      <img src="/media/imagens/mosaico_1_800.png" class="card-img-top position-relative" alt="descrição da imagem">
    </div>
    <div>
      <h2>About Thiago Palitot</h2>
      <ul>
        <li>43 years old.</li>
        <li>Degree in Advertising and Propaganda.</li>
        <li>Art director / Creative director</li>
        <li>22 years of experience in the market of RN / PE / PB / SE.</li>
        <li>Winner of regional and national awards.</li>
        <li>7 years of work with public clients (government, municipality, legislative assembly, politicians in general and social organizations).</li>
        <li>Extensive experience in public tenders (internal organization, reading / standardization and bidding documents).</li>
        <li>Marketing / Communication Manager</li>
        <li>Industry with 70 stores in 15 Brazilian states.</li>
        <li>Experience with PDV, commercial, logistics, production, stock, system, human resources and processes.</li>
      </ul>
      <p><strong>Contact:</strong></p>
      <ul>
        <li>+55 84 98848.2737</li>
        <li>thiagopalitot@gmail.com</li>
        <li><a href="https://www.linkedin.com/in/thiago-palitot-841585123/">Linkedin</a></li>
        <li><a href="https://www.instagram.com/tpalitot/?hl=pt-br">Instagram</a></li>
        <li><a href="https://www.facebook.com/thiago.palitot">Facebook</a></li>
        <li><a href="https://www.youtube.com/channel/UCqziSdsk-PC9nuBWlKVzJvg">YouTube</a></li>
      </ul>
    </div>
  </div>
</div>
{% endblock %}

portfolio/templates/base.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
    <link href="https://fonts.cdnfonts.com/css/gotham" rel="stylesheet">
    
</head>
<body>
    <header>
        <div class="container-fluid">
            <div class="row mt-4">
                <div class="col text-left d-flex align-items-center">
                    <nav style="margin-left: 20px;">
                        <ul class="navbar-nav">
                            <li class="row nav-item">
                                <a class="nav-link" href="{% url 'portfolio:project_list' %}" style="color:black; font-weight:bold; font-family:'Gotham 700', sans-serif; font-size: 250%">Thiago Palitot</a>
                                <span style="margin:0 10px;"> </span>
                                <a class="nav-link align-self-center" href="{% url 'portfolio:about' %}" style="color:gray; font-weight:50; font-family:'Gotham', sans-serif; font-size: 250%">about</a>
                            </li>
                        </ul>
                    </nav>
                </div>
                <div class="col text-right">
                    <div class="d-flex justify-content-end align-items-center" style="display: flex;">
                        <a class="btn btn-link m-0 p-0 mt-4" href="https://www.linkedin.com/in/thiago-palitot-841585123/">
                            <img src="/media/imagens/in.png" style="max-height: 16px; max-width: 16px;">
                        </a>
                        <a class="btn btn-link m-0 p-0 mt-4" href="https://www.instagram.com/tpalitot/?hl=pt-br">
                            <img src="/media/imagens/insta.png" style="max-height: 16px; max-width: 16px;">
                        </a>
                        <a class="btn btn-link m-0 p-0 mt-4" href="https://api.whatsapp.com/send?phone=5584988482737">
                            <img src="/media/imagens/whats.png" style="max-height: 16px; max-width: 16px;">
                        </a>
                    </div>
                </div>
                
                
            </div>
        </div>
    </header>
    
      

    <div class="container-fluid">
        {% block content %}{% endblock %}
    </div>

    <footer class="fixed-footer">
      <div class="container">
          <div class="row">
              <div class="col-sm-12 text-center">
                  <button class="btn btn-primary" onclick="window.location.href='../'">Back</button>
              </div>
          </div>
      </div>
    </footer>
  
  

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
</body>
</html>

portfolio/templates/home.html
{% extends 'base.html' %}

{% block title %}Projetos{% endblock %}

{% block content %}
<div class="row">
  {% for projeto in projetos %}
  <div class="col-md-6 mb-4">
    <div class="card">
      <a href="{% url 'portfolio:project_detail' projeto.pk %}">
        <img src="{{ projeto.imagem_set.first.imagem.url }}" class="card-img-top" alt="{{ projeto.nome }}">
      </a>
      
    </div>
  </div>
  {% endfor %}
</div>
{% endblock %}

portfolio/templates/project_detail.html
{% extends 'base.html' %}
<!-- Bootstrap CSS -->
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.6.0/css/bootstrap.min.css" integrity="sha512-9P6UJHgUztwW8nHULbRlLUVb1nQmkWf8GvNQYZc/qbwN+kJdMwW8MBaD+bz1TGrT61TfL4pIPc4Z/r9ABryFbA==" crossorigin="anonymous" referrerpolicy="no-referrer" />

<!-- jQuery -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js" integrity="sha512-fTsL4+6Vg77z5Zn9zVgAd+fZn0aPaWqrxDvhpz4jJx86nJ/pa/4Yo4teX9k1/UKiXQGKwALbF7vMJM90WfL7Nw==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>

<!-- Bootstrap JS -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.6.0/js/bootstrap.min.js" integrity="sha512-zUWfjJyvRbO68gM6eGR+mg/zoZQjXVzNyLcOnJyf6nzF0wUkkv6IWGcS/pxpOgTzT9XAbfQ4YBBlO4LsNwOanw==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>

{% block content %}
<div class="row">
    <div class="col-md-6">
      <h2>{{ projeto.nome }}</h2>
      <p>{{ projeto.descricao }}</p>
     
    </div>
    <div class="col-md-6">
      <p class="font-weight-bold">Cliente:</p>
      <p>{{ projeto.cliente }}</p>
    </div>
    
    {% if imagens %}
    <div class="row mt-1 no-gutters d-flex" img {
      max-width:100%;
      height:auto;
      object-fit: cover;sou
    }>
      {% for imagem in imagens|slice:"1:" %}
        <div class="col-md-6 p-0">
          <img src="{{ imagem.imagem.url }}" class="card-img-top" alt="{{ imagem.descricao }}" data-toggle="modal" data-target="#imagem-modal" style="border-radius: 0;">
          <div class="modal fade" id="imagem-modal" tabindex="-1" aria-labelledby="imagem-modal-label" aria-hidden="true">
            <div class="modal-dialog modal-dialog-centered modal-lg">
              <div class="modal-content">
                <div class="modal-header">
                  <h5 class="modal-title" id="imagem-modal-label">{{ imagem.descricao }}</h5>
                  <button type="button" class="close" data-dismiss="modal" aria-label="Fechar">
                    <span aria-hidden="true">&times;</span>
                  </button>
                </div>
                <div class="modal-body">
                  <img src="{{ imagem.imagem.url }}" class="img-fluid"/>
                </div>
              </div>
            </div>
          </div>
        </div>
      {% endfor %}
    </div>
  {% endif %}
</div>  
    

    {% if youtube_id %}
        <div class="embed-responsive embed-responsive-16by9">
            <iframe class="embed-responsive-item" src="https://www.youtube.com/embed/{{ youtube_id }}"></iframe>
        </div>
    {% endif %}      
{% endblock %}

portfolio/templates/project_list.html
{% extends "base.html" %}

{% block content %}
<div class="row mt-1 no-gutters">
  {% for projeto in projetos %}
  <div class="col-md-6">
      <a href="{% url 'portfolio:project_detail' projeto.pk %}">
        <img src="{{ projeto.imagem_set.first.imagem.url }}" class="card-img-top position-relative rounded-0" alt="{{ projeto.nome }}"
              .card-img-top {
                width: 100%;
                height: 100%;
                object-fit: cover;
              }
              style="max-height: 200px;">
      </a>
  </div>
  {% endfor %}
</div>
{% endblock %}

portfolio/templates/project_listold.html
{% extends "base.html" %}

{% block content %}
<div class="row">
  {% for projeto in projetos %}
  <div class="col-md-6 mb-4">
      <div class="card">
          <a href="{% url 'portfolio:project_detail' projeto.pk %}">
              <img src="{{ projeto.imagem_set.first.imagem.url }}" class="card-img-top position-relative" alt="{{ projeto.nome }}">
          </a>
      </div>
  </div>
  {% endfor %}
</div>
{% endblock %}